general {
    lock_cmd = pidof gtklock || gtklock -s ~/.config/hypr/gtklock/style.css
}

listener {
    timeout = 3600
    on-timeout = gtklock -s ~/.config/hypr/gtklock/style.css & systemctl hibernate
}